project:
  type: book
  output-dir: docs

book:
  title: "Data Science at SHARE Creative"
  author: "Jamie Hudson"
  date: "5/7/2024"
  chapters:
    - index.qmd
    - summary.qmd
    - project_management.qmd
    - project_players.qmd
    - peaks_pits_workflow.qmd
    - ai_landscape_workflow.qmd
    - glossary.qmd
    - resources.qmd

bibliography: references.bib

format:
  html:
    theme: lumen
  pdf:
    documentclass: scrreprt

editor: source

