project:
  type: book
  output-dir: docs

book:
  title: "Data Science at SHARE Creative"
  author: ""
  sidebar: 
    # style: floating
    # background: light
    search: true
    collapse-level: 1
    border: true
  chapters:
    - part: "Introduction"
      chapters:
        - index.qmd
        - summary.qmd
    - text: "---"
    - part: "Case Studies"
      chapters:
        - peaks_pits_workflow.qmd
        - conversation_landscape.qmd
    - text: "---"
    - part: "Project work"
      chapters:
        - project_management.qmd
        - project_players.qmd
    - text: "---"
    - part: "Development"
      chapters:
        - packages.qmd
    - text: "---"
    - part: "Tips and Tricks"
      chapters:
        - data_cleaning.qmd
  bread-crumbs: false
    # - code_best_practices.qmd
    # - glossary.qmd
    # - resources.qmd
    


bibliography: references.bib

format:
  html:
    theme: 
      light: lumen
      dark: [lumen, theme-dark.scss]
  pdf:
    documentclass: scrreprt

editor: source

